@schema = http
@hostname = localhost
@port = 8080
@host = {{schema}}://{{hostname}}:{{port}}

@token = {{Login.response.body.token}}
@userId = {{CreateUser.response.body.id}}

###

GET {{host}}
X-Health-Check: 1

###

# @name GetUsers

GET {{host}}/user
Authorization: Bearer {{token}}

###

# @name CreateUser

POST {{host}}/user
Content-Type: application/json

{
    "name": "Steven",
    "email": "steven_1@test.com",
    "password": "test1234"
}

###

# @name GetUser

GET {{host}}/user/{{userId}}
Authorization: Bearer {{token}}

###

# @name UpdateUser

PUT {{host}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Steven Bengtson"
}

###

# @name DeleteUser

DELETE {{host}}/user/{{userId}}
Authorization: Bearer {{token}}

###

# @name Login

POST {{host}}/auth
Content-Type: application/json

{
    "email": "steven_1@test.com",
    "password": "test1234"
}

###

# @name RefreshToken

PUT {{host}}/auth/refresh
Content-Type: application/json
Authorization: Bearer {{token}}

{}
